export const GET_ERRORS = "GET_ERRORS";
export const GET_ERRORS_LOGIN = "GET_ERRORS";
export const JUST_REGISTERED_STATUS = "JUST_REGISTERED_STATUS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_EMAILPASS_USER = "GET_EMAILPASS_USER";
